### ISSUE TITLE
Home route retaining crumb(s) of last page

### ISSUE THREAD

**Issue by ghost** [nedavniat/express-seo-breadcrumbs#1]
I seem to be having a problem, the breadcrumb on my index page will return the crumb(s) of the last page visited (only the homepage, as detailed below).

`Home -> News -> Article -> News` will return the correct breadcrumb `Home / News` going back further from there to `News -> Home` will return `Home / News`

`Home -> News -> Article -> Home` will return the result `Home / News / Article`

**Home route**
```javascript
const express = require('express');

const router = express.Router();

router.get('/', (req, res) => {
  req.breadcrumbs({
    name: 'Home',
    url: '//localhost:3000'
  });

  const breadcrumbs = req.breadcrumbs();

  res.render('index', {
    breadcrumbs,
    title: 'Homepage'
  });
});

module.exports = router;
```

**Breadcrumbs partial**
```html
<section class="breadcrumbs">
  <div class="container">
    <ol class="breadcrumb">
      <% if(breadcrumbs){ %>
        <% for(var i = 0; i < breadcrumbs.length; i++){ %>
          <% if(i === (breadcrumbs.length - 1)){ %>
            <li class="active">
              <%= breadcrumbs[i].name.charAt(0).toUpperCase() + breadcrumbs[i].name.slice(1) %>
            </li>
          <%} else {%>
            <li>
              <a href="//<%= breadcrumbs[i].url %>"><%= breadcrumbs[i].name.charAt(0).toUpperCase() + breadcrumbs[i].name.slice(1) %></a>
            </li>
          <% } %>
        <% } %>
      <% } %>
    </ol>
  </div>
</section>
```

**Comment by ghost** [comment]
Closing due to no reply from the package author, also I moved to another means of breadcrumbs as I couldn't get this issue resolved.

**Comment by horoscop** [comment]
Hi! Could you please tell me which express breadcrumbs npm module you're using?

Thank you!
